language: java
install: true

jdk:
- openjdk11

script:
  - ./gradlew build

deploy:
  - provider: script
    script: ./gradlew publish
    skip_cleanup: true
    dry-run: false
    on:
      tags: true
      branch: master