language: java
install: true

jdk:
- openjdk8

before_script:
- cd ecore2bikeshed

script:
  - ./gradlew build

deploy:
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    dry-run: false
    on:
      tags: true
      repo: opencaesar/ecore-bikeshed
      branch: master